"""Planner for task planning and skill sequence generation."""

import json
from typing import Dict, List, Optional
from dataclasses import dataclass

from .llm_client import LLMClient
from .errors import PlannerError


@dataclass
class ExecutionPlan:
    """Execution plan generated by Planner."""
    intent: str
    steps: List[Dict]
    estimated_tokens: int = 0

    def to_dict(self) -> Dict:
        """Convert to dictionary."""
        return {
            "intent": self.intent,
            "steps": self.steps,
            "estimated_tokens": self.estimated_tokens
        }

    def filter_by_confidence(self, threshold: float = 0.5) -> "ExecutionPlan":
        """Filter steps by confidence threshold.

        Args:
            threshold: Minimum confidence level

        Returns:
            New ExecutionPlan with filtered steps
        """
        filtered_steps = [
            step for step in self.steps
            if step.get("confidence", 0) >= threshold
        ]

        return ExecutionPlan(
            intent=self.intent,
            steps=filtered_steps,
            estimated_tokens=self.estimated_tokens
        )


class Planner:
    """Task planner that generates execution plans.

    Analyzes user input and available skills to create
    a step-by-step execution plan.
    """

    def __init__(
        self,
        llm_client: LLMClient,
        confidence_threshold: float = 0.5
    ):
        """Initialize Planner.

        Args:
            llm_client: LLM client for planning
            confidence_threshold: Minimum confidence for steps
        """
        self.llm = llm_client
        self.confidence_threshold = confidence_threshold

    def generate_plan(
        self,
        user_input: str,
        available_skills: Dict,
        conversation_history: List[Dict] = None
    ) -> ExecutionPlan:
        """Generate execution plan for user request.

        Args:
            user_input: User's request
            available_skills: Dictionary of available skills
            conversation_history: Optional conversation history

        Returns:
            ExecutionPlan with steps

        Raises:
            PlannerError: If planning fails
        """
        # Format available skills for prompt
        skills_desc = self._format_skills(available_skills)

        # Build prompt
        prompt = self._build_planning_prompt(
            user_input,
            skills_desc,
            conversation_history
        )

        try:
            response = self.llm.invoke(prompt)

            # Extract JSON from markdown code blocks if present
            json_str = response.strip()
            if json_str.startswith("```"):
                # Find the JSON content within the code block
                lines = json_str.split("\n")
                json_lines = []
                in_json = False
                for line in lines:
                    if line.startswith("```json") or line.startswith("```"):
                        in_json = not in_json if json_lines else True
                        continue
                    if in_json:
                        json_lines.append(line)
                json_str = "\n".join(json_lines)

            plan_data = json.loads(json_str)

            # Validate plan structure
            if "steps" not in plan_data:
                raise PlannerError("Invalid plan: missing 'steps' field")

            # Create ExecutionPlan
            plan = ExecutionPlan(
                intent=plan_data.get("intent", ""),
                steps=plan_data["steps"],
                estimated_tokens=plan_data.get("estimated_tokens", 0)
            )

            # Filter by confidence threshold
            filtered_plan = plan.filter_by_confidence(self.confidence_threshold)

            if not filtered_plan.steps:
                raise PlannerError(
                    "No steps with sufficient confidence. "
                    f"Threshold: {self.confidence_threshold}"
                )

            return filtered_plan

        except json.JSONDecodeError as e:
            raise PlannerError(f"Failed to parse plan response: {e}")
        except Exception as e:
            raise PlannerError(f"Planning failed: {e}")

    def _build_planning_prompt(
        self,
        user_input: str,
        skills_desc: str,
        conversation_history: List[Dict] = None
    ) -> str:
        """Build prompt for planning."""
        history_context = ""
        if conversation_history:
            history_context = f"\nPrevious conversation:\n{self._format_history(conversation_history)}\n"

        prompt = f"""You are a task planning agent. Analyze the user request and create an execution plan using available skills.

User Request: {user_input}{history_context}

Available Skills:
{skills_desc}

Instructions:
1. Understand the user's intent
2. Break down the task into steps using available skills
3. Each step should specify:
   - skill: Name of the skill to use
   - sub_task: Specific sub-task description for that skill
   - confidence: Your confidence (0-1) that this step is correct
4. Steps should be sequential when later steps depend on earlier results
5. Filter out steps with confidence < 0.5

Respond in JSON format:
{{
    "intent": "Brief description of user's overall intent",
    "steps": [
        {{
            "skill": "skill_name",
            "sub_task": "Specific description of what this step should accomplish",
            "confidence": 0.95
        }}
    ],
    "estimated_tokens": 5000
}}
"""
        return prompt

    def _format_skills(self, available_skills: Dict) -> str:
        """Format available skills for prompt."""
        lines = []
        for name, skill in available_skills.items():
            lines.append(
                f"- {name}: {skill.description}\n"
                f"  Triggers: {', '.join(skill.triggers)}\n"
                f"  Tags: {', '.join(skill.tags)}"
            )
        return "\n".join(lines)

    def _format_history(self, history: List[Dict]) -> str:
        """Format conversation history."""
        lines = []
        for msg in history[-5:]:  # Only last 5 messages
            role = msg.get("role", "unknown")
            content = msg.get("content", "")[:100]
            lines.append(f"  {role}: {content}...")
        return "\n".join(lines)

    def refine_plan(
        self,
        original_plan: ExecutionPlan,
        feedback: str
    ) -> ExecutionPlan:
        """Refine plan based on feedback.

        Args:
            original_plan: Original execution plan
            feedback: Feedback for improvement

        Returns:
            Refined ExecutionPlan
        """
        prompt = f"""Refine the following execution plan based on feedback:

Original Plan:
{json.dumps(original_plan.to_dict(), indent=2)}

Feedback: {feedback}

Please provide an improved plan in the same JSON format.
"""

        try:
            response = self.llm.invoke(prompt)
            plan_data = json.loads(response)

            return ExecutionPlan(
                intent=plan_data.get("intent", original_plan.intent),
                steps=plan_data.get("steps", original_plan.steps),
                estimated_tokens=plan_data.get("estimated_tokens", original_plan.estimated_tokens)
            )

        except Exception:
            # Return original if refinement fails
            return original_plan
